### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by Corinthian72** [Pum-purum/sale.order.ajax#3]
Неплохо было бы пошагово описать изменения, внесённые в файлы шаблона sale.order.ajax, чтобы люди понимали как именно реализовано раскрытие блоков (и другие правки). Это позволит гораздо проще интегрировать эти изменения в случае, когда на сайте уже используется кастомизированный шаблон и полностью его заменять - не вариант.

**Comment by Pum-purum** [comment]
Тут 7000 строк кода, я не очень представляю себе, как это можно словами описать. Только держать в голове.
